### ISSUE TITLE
[sddm-kcm]: brainstorm for adding a way to download themes from the store via ghns

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-general#46]
Now since login is a sensible area to customize via theming, the question is:
Can we encapsulate the theming in such a way that people make many nice themes again like for kdm4 and we dont run any much higher risk than with other ghns?

I thought to also force implement the "approval" flag for this category, that also warns if a product updated again after the last approval date.

Just some thoughts here before we release any posdible implementation.

**Comment by star-buck** [comment]
Current themes in store:
https://store.kde.org/browse/cat/101/

**Comment by davidedmundson** [comment]
Got two minor problems.

Firstly, there's something wrong on the server:

In the file https://store.kde.org/ocs/v1/content/categories

listings should look like:
<category>
<id>104</id>
<name>Plasma Theme</name>
</category>
<category>
<id>105</id>
<name>Plasma 5 Plasmoid</name>
</category>

Whereas SDDM's one is:
<category>
<id>101</id>
<name>101</name>
</category>

Without a name set,  this causes a problem for me filtering.

That's server side, could you look into it please?

---

Second problem is that currently all the themes are currently structued differently, so they won't all work with the install button, but I'll make an effort to document a specific format so that problem goes away in time.

**Comment by star-buck** [comment]
The idea was using numbers , as the Category names might change, which they otherwise cant.
But now that we built a translator for legacy names, we might as well use this for new GHNS categories, so I changed it to 
101 SDDM Theme

**Comment by davidedmundson** [comment]
That worked, thanks.

This is now all merged, and will be in 5.9

**Comment by star-buck** [comment]
another one done
